baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Peiyu Li"
    description = "Website title"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Peiyu Li"
        photo = "_Mochi.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "#"
            title = "LinkedIn"	
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/PeiyuBellaLi"
            title = "GitHub"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        [[params.aboutme.list]]
            description = "Undergraduate student with proven organizational, and analytical skills."
        [[params.aboutme.list]]
            description = "Highly motivated, conscientious, and exceptionally patient individual who loves to work in a dynamic, fast-paced environment."
        [[params.aboutme.list]]
            description = "Fast learner with quick adaption to new concepts, and technologies."
        [[params.aboutme.list]]
            description = "Excellent team player with great communication and interpersonal skills."
        [[params.aboutme.list]]
            description = "Seeking to apply my abilities to intern positions such as Data Analyst."

    # Social Experience section
    [params.experience]
        title = "Social Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Teaching Assistant"
            dates = "June 2019 - July 2019"
            company = "JNC Study Abroad Platform & Jinan University"
            location = "Guangzhou, Guangdong, China"
            details = """*  Assisted Prof. Stefan Kautsch in Introduction to Astronomy, Prof. Yan Shi in Introduction to Statistics, and Prof. Hynek Boril in Linear Algebra. \n * Registered student information, recorded attendance, prepared lecture materials. \n * Provided weekly tutorial sessions, after class Q&A, and marking. \n * Built solid organizational and communication skills. """
        [[params.experience.list]]
            position = "Volunteer Teacher"
            dates = "May 2019 – June 2019"
            company = "Liang'an National Secondary School"
            location = "Liang'an Village, Zhongshan County, Hezhou, Guangxi, China"
            details = """* Worked in an impoverished area as a volunteer from the Chinese Volunteer Association in University of Toronto. \n * Taught Grade 9 students English and Mathematics, and helped them to prepare for the senior high school entrance examination. \n * Visited and supported families of those students who are in relatively poor financial condition but have excellent academic performance. \n * Sponsored, designed, organized and hosted an event to celebrate a local festival."""

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"
        [[params.education.list]]
            degree = "Honors Bachelor of Science"
            college = "University of Toronto - St. George Campus"
            dates = "2018 - present"
            details = """* Specialist in Statistical Science \n * Focus in Social Psychology \n * Mathematics Minor"""

    # Statistical Project section
    [params.project]
        title = "Statistical Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Analyzing the Effects of Age Groups on the Outcomes of COVID-19"
            url = "#"
            description = """* Analyzed if people older than 60 are more likely to die due to COVID-19 based on the COVID-19 case details data in Canada. \n * The conclusion is being older than 60 years old will significantly increase the probability of mortality. \n * Used propensity score matching and logistic regression. \n * Evaluate the performance of the model by using ROC curve."""
        [[params.project.list]]
            title = "Prediction of the Overall Popular Vote of the 2020 American Federal Election"
            url = "#"
            description = """Used logistic regression with the post-stratification technique. \n * The prediction of the popular vote for Donald Trump is 40%. (Predicted before the actual 2020 American Federal Election.) \n * The model was selected by comparing AIC values. \n * Confusion matrix and ROC curve were used to check the accuracy of the model."""
        [[params.project.list]]
            title = "Prediction of the admission rates for colleges and universities in US"
            url = "#"
            description = "* Investigated which of the factors shows the most significant relationship with admission rate, such as percentage of undergraduates receiving Pell grant. \n * The model was selected using stepwise selection based on AIC and BIC values. \n * Created residual plots and Normal Q-Q plot to diagnose the model \n * Applied power transform to fix non-linearity"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python"
            skillrating = 80
        [[params.skill.list]]
            skill = "R"
            skillrating = 80
        [[params.skill.list]]
            skill = "SQL"
            skillrating = 70
        [[params.skill.list]]
            skill = "Git"
            skillrating = 60
        [[params.skill.list]]
            skill = "Microsoft Office"
            skillrating = 80
        [[params.skill.list]]
            skill = "SAS Certified Specialist: Base Programming"
            skillrating = 100